# Generated by Django 4.2.28 on 2026-05-07 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_testtask_scores'),
        ('encyclopedia', '0007_sync_current_models'),
        ('tasks', '0005_task_related_concepts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Тег (блок задач)', 'verbose_name_plural': 'Теги задач'},
        ),
        migrations.AlterField(
            model_name='task',
            name='concept',
            field=models.ForeignKey(blank=True, help_text='Основной концепт, который проверяет задача.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='encyclopedia.concept', verbose_name='Главное понятие'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Novice (Основы)'), (2, 'Beginner (Логика)'), (3, 'Intermediate (Алгоритмы)')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0, help_text='Позиция внутри тега; должна быть уникальной для блока.', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.tasktag', verbose_name='Тег (блок)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('code', 'Написание кода'), ('choice', 'Выбор ответа (тест)')], default='code', max_length=20, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='usertaskattempt',
            name='test_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attempts', to='testing.testattempt', verbose_name='Попытка теста'),
        ),
    ]
