# Generated by Django 4.2.28 on 2026-04-06 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_alter_conceptrelation_relation_type'),
        ('core', '0004_material_concept'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterField(
            model_name='material',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='encyclopedia.concept', verbose_name='Связанный концепт'),
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(verbose_name='Содержание (HTML)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='material',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок (сортировка)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
