# Generated by Django 4.2.28 on 2026-04-26 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_material_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Первое открытие')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее открытие')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Отмечен как изученный')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='Количество открытий')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='core.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс по материалу',
                'verbose_name_plural': 'Прогресс по материалам',
                'ordering': ['-last_opened_at', '-completed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='materialprogress',
            constraint=models.UniqueConstraint(fields=('user', 'material'), name='unique_user_material_progress'),
        ),
    ]
