# Generated by Django 4.2.28 on 2026-05-07 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_move_materials_to_materials_app'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS core_userprofile (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        experience_points integer NOT NULL,
                        current_level integer NOT NULL,
                        user_id integer NOT NULL UNIQUE
                            REFERENCES auth_user(id)
                            DEFERRABLE INITIALLY DEFERRED
                    );
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='UserProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('experience_points', models.IntegerField(default=0)),
                        ('current_level', models.IntegerField(default=1)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
        ),
    ]
