"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable or fallback to dev key (fixing Security Problem #2)
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-=1&0!&0!&0!&0!&0!&0!&0!&0!&0!&0!&0!&0!&0!&0!&0!&0!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',  # Для генерации ER-диаграмм и других утилит
    'apps.core',
    'apps.materials',
    'apps.simulator',
    'apps.tasks',
    'apps.encyclopedia',
    'apps.testing',
    'django_cleanup.apps.CleanupConfig',  # Automatically deletes old media files
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': dj_database_url.config(
        default=f"postgres://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'
# Время «открыт/закрыт» в тестах из формы считается в этой зоне (иначе 22:16 = 22:16 UTC, а не по Москве)
TEST_DATETIME_TIMEZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'core:profile'
LOGOUT_REDIRECT_URL = 'core:home'
CSRF_FAILURE_VIEW = 'apps.core.views.csrf_failure'

# Sandbox Configuration
SANDBOX_EXECUTOR = os.getenv('SANDBOX_EXECUTOR', 'docker').strip().lower()
SANDBOX_IMAGE = os.getenv('SANDBOX_IMAGE', 'clustering-sandbox:latest').strip()
SANDBOX_TIMEOUT_SECONDS = int(os.getenv('SANDBOX_TIMEOUT_SECONDS', '5'))
SANDBOX_MAX_INSTRUCTIONS = int(os.getenv('SANDBOX_MAX_INSTRUCTIONS', '200000'))
SANDBOX_MEMORY_LIMIT = os.getenv('SANDBOX_MEMORY_LIMIT', '256m').strip()
SANDBOX_CPU_LIMIT = float(os.getenv('SANDBOX_CPU_LIMIT', '0.5'))
SANDBOX_PIDS_LIMIT = int(os.getenv('SANDBOX_PIDS_LIMIT', '64'))
SANDBOX_COMPARISON_ATOL = float(os.getenv('SANDBOX_COMPARISON_ATOL', '0.01'))
SANDBOX_DISABLE_NETWORK = os.getenv('SANDBOX_DISABLE_NETWORK', 'True') == 'True'
SANDBOX_ALLOW_INPROCESS_FALLBACK = (
    os.getenv('SANDBOX_ALLOW_INPROCESS_FALLBACK', 'True' if DEBUG else 'False') == 'True'
)

# Email Configuration (Development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'Clustering Trainer <noreply@clustering-trainer.local>'

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
