# Generated by Django 4.2.28 on 2026-03-01 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0002_alter_test_tasks_to_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Краткое название (тема)')),
                ('content', models.TextField(verbose_name='Текст задания / Условие')),
                ('question_type', models.CharField(choices=[('text', 'Текстовый ответ / Код'), ('file', 'Загрузка файла (отчет/датасет)')], default='text', max_length=10, verbose_name='Тип ответа')),
                ('max_score', models.PositiveIntegerField(default=10, verbose_name='Максимальный балл')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='teacher_materials/', verbose_name='Прикрепленный материал для студента (CSV, PDF и т.д.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Вопрос / Задание',
                'verbose_name_plural': 'Банк вопросов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тест (Контрольная)', 'verbose_name_plural': 'Тесты (Контрольные)'},
        ),
        migrations.AlterModelOptions(
            name='testattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Попытка прохождения', 'verbose_name_plural': 'Попытки прохождения'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='tasks',
        ),
        migrations.AddField(
            model_name='testattempt',
            name='is_graded',
            field=models.BooleanField(default=False, verbose_name='Проверено преподавателем'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Общий комментарий к работе'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='total_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговый балл'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Лимит времени (минут)'),
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='tests', to='testing.question', verbose_name='Вопросы из банка'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Текстовый ответ / Код студента')),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='student_answers/', verbose_name='Загруженный файл ответа')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Выставленный балл')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Обратная связь (комментарий преподавателя)')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='testing.question')),
            ],
            options={
                'verbose_name': 'Ответ студента',
                'verbose_name_plural': 'Ответы студентов',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
