# Generated by Django 4.2.28 on 2026-03-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_question_alter_test_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
