# Generated by Django 4.2.28 on 2026-02-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptrelation',
            name='relation_type',
            field=models.CharField(choices=[('IS_A', 'Является (Is A)'), ('PART_OF', 'Является частью'), ('USES', 'Использует'), ('DEPENDS', 'Зависит от (Пререквизит)'), ('RELATED', 'Связано с'), ('EXTENDS', 'Расширяет метод'), ('SPECIAL_CASE', 'Частный случай')], max_length=20, verbose_name='Тип связи'),
        ),
    ]
