# Generated by Django 4.2.28 on 2026-05-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0006_course_module_simulator_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='uri',
            field=models.CharField(help_text='Unique ID from OWL ontology', max_length=255, unique=True),
        ),
    ]
