# Generated by Django 4.2.28 on 2026-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0007_sync_current_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodulesimulator',
            name='preset',
            field=models.CharField(blank=True, choices=[('', 'Без стартового набора'), ('blobs', 'Облака'), ('moons', 'Луны'), ('circles', 'Кольца'), ('grid', 'Сетка'), ('hierarchy', 'Иерархия кластеров'), ('dense_sparse', 'Плотный и разреженный кластеры'), ('anisotropic', 'Вытянутые группы'), ('outliers', 'Шум и выбросы'), ('many_blobs', 'Много групп'), ('bridge', 'Мост между группами')], max_length=80, verbose_name='Стартовый набор данных'),
        ),
    ]
